version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      _JAVA_OPTIONS: ${JAVA_OPTIONS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
